{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dials
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dials_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dials/dials_{{ version }}.tar.gz
  sha256: 24660e7200cca6f2c63dc70dec3702a2bed027e02639c7c66d5ebd2f0f7148fe

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-dicedesign
    - r-dplyr >=0.8.5
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-pillar
    - r-purrr
    - r-rlang >=1.0.1
    - r-scales
    - r-tibble
    - r-vctrs >=0.3.8
    - r-withr
  run:
    - r-base
    - r-cli
    - r-dicedesign
    - r-dplyr >=0.8.5
    - r-glue
    - r-hardhat >=1.1.0
    - r-lifecycle
    - r-pillar
    - r-purrr
    - r-rlang >=1.0.1
    - r-scales
    - r-tibble
    - r-vctrs >=0.3.8
    - r-withr

test:
  commands:
    - $R -e "library('dials')"           # [not win]
    - "\"%R%\" -e \"library('dials')\""  # [win]

about:
  home: https://tidymodels.github.io/dials
  license: MIT
  summary: Many models contain tuning parameters (i.e. parameters that cannot be directly estimated from the data). These tools can be used to define objects for creating, simulating, or validating values for such parameters.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: dials
# Version: 0.0.3
# Title: Tools for Creating Tuning Parameter Values
# Description: Many models contain tuning parameters (i.e. parameters that cannot be directly estimated from the data). These tools can be used to define objects for creating, simulating, or validating values for such parameters.
# Authors@R: c( person(given = "Max", family = "Kuhn", email = "max@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"))
# License: GPL-2
# URL: https://tidymodels.github.io/dials
# BugReports: https://github.com/tidymodels/dials/issues
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Depends: scales, R (>= 2.10)
# Imports: glue, purrr, tibble, rlang, utils, withr, DiceDesign, dplyr
# Suggests: testthat, knitr, rpart, covr, kernlab, xml2
# NeedsCompilation: no
# Packaged: 2019-10-01 00:25:51 UTC; max
# Author: Max Kuhn [aut, cre], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-01 05:00:02 UTC
