{% set version = "0.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dials
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dials_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dials/dials_{{ version }}.tar.gz
  sha256: 023d88863344dc81527e47b5669df01b000577ac31dc0cbd5611301fd532d87a

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-dplyr
    - r-glue
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-dplyr
    - r-glue
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('dials')"           # [not win]
    - "\"%R%\" -e \"library('dials')\""  # [win]

about:
  home: https://tidymodels.github.io/dials
  license: GPL-2
  summary: 'Many models contain tuning parameters (i.e. parameters that cannot be directly estimated
    from the data). These tools can be used to define objects for creating, simulating,
    or validating values for such parameters. '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - philip-khor
