{% set version = "0.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dials
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dials_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dials/dials_{{ version }}.tar.gz
  sha256: e039f65dca34700749a5e4050b293a6e28a7c60392bbc42545783496a691dceb

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dicedesign
    - r-dplyr
    - r-glue
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-dicedesign
    - r-dplyr
    - r-glue
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('dials')"           # [not win]
    - "\"%R%\" -e \"library('dials')\""  # [win]

about:
  home: https://tidymodels.github.io/dials
  license: GPL-2
  summary: Many models contain tuning parameters (i.e. parameters that cannot be directly estimated from the data). These tools can be used to define objects for
    creating, simulating, or validating values for such parameters.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: dials
# Version: 0.0.3
# Title: Tools for Creating Tuning Parameter Values
# Description: Many models contain tuning parameters (i.e. parameters that cannot be directly estimated from the data). These tools can be used to define objects for creating, simulating, or validating values for such parameters.
# Authors@R: c( person(given = "Max", family = "Kuhn", email = "max@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"))
# License: GPL-2
# URL: https://tidymodels.github.io/dials
# BugReports: https://github.com/tidymodels/dials/issues
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Depends: scales, R (>= 2.10)
# Imports: glue, purrr, tibble, rlang, utils, withr, DiceDesign, dplyr
# Suggests: testthat, knitr, rpart, covr, kernlab, xml2
# NeedsCompilation: no
# Packaged: 2019-10-01 00:25:51 UTC; max
# Author: Max Kuhn [aut, cre], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-01 05:00:02 UTC
