appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: A+DCrAvneF1hRb9SOcmZtIgwnKucZZCdfuMxA8uMyz1PltutkO6A3/ByrkpdLAgCuuiYefwrItMa/Y1SZf7o0xPckBN1yuoDbzASEu9g/rZK+deZSWVAmMiH285+XghcYkuj/cmpcZsAQHQZ1/gvRZd1GXfwEqVUIiSEpTWRPUVpP6h8EagQJRzS/SfHnEPWCAoCbibM8LYD0lUjPBG7/jFtFRVleFGsIQt/USlX5HlVj9Ytjn1paHlGOdLy06WLn7qq/20psPDxCrdP6e/wNzjfailanEjkPHlyTZZW/EJg0PnPpxFM6YVGg2um7WU0cIknyZcAhvfPCj+jSqzdODIGpP2QKkmiDTtaIli5DZ8nlSQEOnr/jmui8RtcPsBXc682YOGqdSK51KeebfOvr7A8ETVA0vXCJ3YPZn9t9WDJQqFTD9S+Lt26dMNbqPEPQqn91fID9JNBCY3NQ5S/Z2xDPo8EAAjUiRk1PDiO6dgSCSoQMcScovdWE4UW/gJYSTUZ0MWObFWQelyZWWmehGCbNX5XGWojHxuqq5iOtj0/K5LH3CQmgTqaD3b2sNwJNCjIqbVi5H7XmUCjwLPOJSHJ4xU4IWTsslWp/AjYIkAO+RuNJYBRHeQ3I0yw1X/CrF8mv7R8Vmn+mL+uQVJzj3+ZRaMT6P0cP/Cga54rjL4=}
bot:
  automerge: true
